services:
  - type: web
    name: django_app  # change to your preferred app name
    env: python
    buildCommand: pip install -r requirements.txt
    buildCommand: python manage.py collectstatic --noinput
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-postgres-db
          property: connectionString
      - key: DEBUG
        value: false
