services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-postgres-db   # your PostgreSQL DB name on Render
          property: connectionString
      - key: DEBUG
        value: false
