# Generated by Django 5.2.4 on 2025-07-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_formentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='blog_images/129780.jpg', null=True, upload_to='blog_images/'),
        ),
    ]
